public class ArithmeticClass {

    public String getNum1() {
        return null;
    }


    public PageReference remainder() {
        return null;
    }


    public PageReference multiplication() {
        return null;
    }


    public PageReference division() {
        return null;
    }


    public PageReference subtraction() {
        return null;
    }


    public PageReference addition() {
        return null;
    }

}